In [1]:
arr1 = ['pune','mumbai','kashi','Goa','nagpur','surat','chennai']

In [2]:
type(arr1)

list

In [3]:
arr1[0]

'pune'

In [4]:
import numpy
arr2 =numpy.array([10,20,30,40,50])

In [5]:
type(arr2)

numpy.ndarray

In [6]:
print(arr2)

[10 20 30 40 50]


In [8]:
arr2

array([10, 20, 30, 40, 50])

In [11]:
arr3 =numpy.array((100,200,300,400,500))

In [12]:
type(arr3)

numpy.ndarray

In [13]:
import numpy as np
a0 =np.array(10)

In [14]:
print(a0)

10


In [15]:
a0.ndim# for dimension

0

In [16]:
a0

array(10)

In [17]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [18]:
a1.ndim

1

In [19]:
a2 = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])

In [20]:
a2

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [22]:
a2.ndim # for 2  dimensional arrays

2

In [23]:
a3 = np.array([[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]])

In [24]:
a3

array([[[   1,    2,    3],
        [  10,   20,   30]],

       [[ 100,  200,  300],
        [1000, 2000, 3000]]])

In [25]:
a3.ndim

3

In [27]:
a4 = np.array([4,44,555],ndmin=4)

In [28]:
a4

array([[[[  4,  44, 555]]]])

In [29]:
a4.ndim

4

In [30]:
amix1 = np.array(['pune',1,'mumbai',2])

In [31]:
amix1

array(['pune', '1', 'mumbai', '2'], dtype='<U11')

In [32]:
type(amix1)

numpy.ndarray

In [33]:
amix2 = np.array([True,5])

In [34]:
amix2

array([1, 5])

In [35]:
amix3 = np.array([False,10])

In [36]:
amix3

array([ 0, 10])

In [38]:
amix4 = np.array([True,'mango',5,4.5]) #not Recommended 

In [39]:
amix4

array(['True', 'mango', '5', '4.5'], dtype='<U32')

In [40]:
amix5 =  np.array([True,'mango',5,4.5],dtype=np.int32)

ValueError: invalid literal for int() with base 10: 'mango'

In [41]:
amix6 =  np.array([True,5,4.5],dtype=np.int32)

In [42]:
amix6

array([1, 5, 4])

In [43]:
amix7 =  np.array([2,5,4.5],dtype=np.float64)

In [44]:
amix7

array([2. , 5. , 4.5])

In [46]:
arr1[0]# index accessing

'pune'

In [47]:
arr2[1]

20

In [48]:
arr2[0]+arr2[1]

30

In [49]:
a2[1,2] # for two dimensional array access
#like first row second column

30

In [50]:
a3[0,0,0]

1

In [51]:
a3[0,0,1]

2

In [52]:
a3[0,0,2]

3

In [53]:
a3[0,1,0]

10

In [54]:
a3[0,1,1]

20

In [55]:
a3[0,1,2]

30

In [56]:
a3[1,0,0]

100

In [57]:
a3[1,0,1]

200

In [58]:
a3[1,0,2]

300

In [59]:
a3[1,1,0]

1000

In [60]:
a3[1,1,1]

2000

In [61]:
a3[1,1,2]

3000

In [62]:
a4[0,0,0,0]

4

In [63]:
a4[0,0,0,1]

44

In [66]:
a4[0,0,0,2]

555

In [67]:
a4[0,0,1,0]

IndexError: index 1 is out of bounds for axis 2 with size 1

In [68]:
arr= np.array([1,2,3,1,2,3,1,2,3])

In [69]:
arr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [70]:
arr2

array([10, 20, 30, 40, 50])

In [72]:
arr2[-2]

40

In [73]:
arr2[-1]

50

In [74]:
arr2[1:]

array([20, 30, 40, 50])

In [75]:
arr2[:3]

array([10, 20, 30])

In [76]:
arr2[:]

array([10, 20, 30, 40, 50])

In [77]:
arr2[1:4:1]

array([20, 30, 40])

In [78]:
arr2[1:4:2]

array([20, 40])

In [80]:
arr2[:4:3]

array([10, 40])

In [81]:
arr2[::4]

array([10, 50])

In [82]:
arr2[::]

array([10, 20, 30, 40, 50])

In [84]:
for i in arr2 :
    print(i)

10
20
30
40
50


In [85]:
x = np.where(arr2==20)# return index value
print(x)

(array([1], dtype=int64),)


In [86]:
x = np.where(arr2==50)
print(x)

(array([4], dtype=int64),)


In [87]:
x = np.where(arr==2)# return list of index
print(x)

(array([1, 4, 7], dtype=int64),)


In [90]:
arraysort = np.array([2,1,5,3,7,5,9,8,5,7,3])

In [91]:
np.sort(arraysort)

array([1, 2, 3, 3, 5, 5, 5, 7, 7, 8, 9])

In [92]:
np.insert(arr2,5,60)

array([10, 20, 30, 40, 50, 60])

In [93]:
for i in arr2:
    print(i)

10
20
30
40
50


In [94]:
np.insert(arraysort,11,10)

array([ 2,  1,  5,  3,  7,  5,  9,  8,  5,  7,  3, 10])

In [95]:
np.insert(arraysort,0,100)

array([100,   2,   1,   5,   3,   7,   5,   9,   8,   5,   7,   3])

In [96]:
np.delete(arraysort,0)

array([1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [97]:
arraysort

array([2, 1, 5, 3, 7, 5, 9, 8, 5, 7, 3])

In [98]:
arrr1= np.insert(arr2,5,60)

In [99]:
arrr1

array([10, 20, 30, 40, 50, 60])

In [103]:
index = [0,1,2]
arr2 = np.delete(arr2,index)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [104]:
arr2

array([40, 50])

In [106]:
# flip = reverse
np.flip(arrr1)

array([60, 50, 40, 30, 20, 10])

In [107]:
arrr1

array([10, 20, 30, 40, 50, 60])

In [108]:
arrflip= np.flip(arrr1)

In [109]:
arrflip

array([60, 50, 40, 30, 20, 10])

In [110]:
arrr1[0]=100

In [111]:
arrr1

array([100,  20,  30,  40,  50,  60])

In [112]:
arrr1.sort()

In [113]:
arrr1

array([ 20,  30,  40,  50,  60, 100])

In [114]:
np.append(arrr1,1000)

array([  20,   30,   40,   50,   60,  100, 1000])

In [132]:
arrr1.append(1000)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [115]:
import array


In [116]:
a2 = array.array('i',[1,2,3,4,5,6,7,8,9,0])

In [117]:
a2

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [118]:
a2.insert(0,100)

In [119]:
a2

array('i', [100, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [120]:
array1 = np.array(a2)

In [121]:
array1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,   0], dtype=int32)

In [122]:
a2.append(1000)

In [125]:
array1 = np.array(a2)
array1

array([ 100,    1,    2,    3,    4,    5,    6,    7,    8,    9,    0,
       1000], dtype=int32)

In [126]:
a2.pop()

1000

In [127]:
array1 = np.array(a2)
array1

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,   0], dtype=int32)

In [129]:
a2.reverse()

In [130]:
a2

array('i', [0, 9, 8, 7, 6, 5, 4, 3, 2, 1, 100])

In [131]:
array1 = np.array(a2)
array1

array([  0,   9,   8,   7,   6,   5,   4,   3,   2,   1, 100], dtype=int32)